name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main  # Adjust to your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the Node.js version compatible with Ionic

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the Angular app (Ionic build)
      - name: Build the app
        run: |
          npm install -g @angular/cli  # Ensure Angular CLI is installed
          ng build --prod

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
