name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main  # Adjust to your target branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use the Node.js version compatible with Ionic

      # Install dependencies
      - name: Install dependencies
        run: npm install

      - name: Inject environment variables
        run: |
          sed -i 's|REPLACE_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_STORAGE_BUCKET|${{ secrets.FIREBASE_STORAGE_BUCKET }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_MESSAGING_SENDER_ID|${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g' src/environments/environment.prod.ts
          sed -i 's|REPLACE_CRYPTO_SECRET|${{ secrets.CRYPTO_SECRET }}|g' src/environments/environment.prod.ts

      # Step 5: Build the Ionic/Angular app
      - name: Build the app
        run: npm run build -- --configuration production

      # Deploy to Firebase Hosting
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting
